### ISSUE TITLE
Support for multiple hashtags

### ISSUE THREAD

**Issue by peterneish** [lazappi/clamour#3]
Would be great to support multiple hashtags - sometimes there are a couple for one event. I can put "#hashtag1 OR #hashtag2" which works, but it breaks the filtering in the wordcloud.

**Comment by lazappi** [comment]
Sorry, I only just saw this (or at least I don't remember seeing it before...). This would be nice and is something I have thought about doing but I probably won't get around to it unless I have a need. Would be more than happy to consider a pull request if you want to give it a crack 😸.

**Comment by lazappi** [comment]
This should be possible in the newest version if you are still interested. Disclaimer: updating might be a bit fiddly.
